name: Deploy production exe

on:
  push:
    branches: 
      - main

jobs:
  docker-compose:
    runs-on: self-host
    environment: docker
    steps:
    # tai code ve vps
      - name: Checkout code
        uses: actions/checkout@v2
    # build code = docker tai vps sau do con BE se chay ow docker trong vps
      - name: Run `docker-compose`
        run: docker compose up --build -d
